/*
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.ide;

import br.edu.unijui.gca.jabuti.JabutiRuntimeModule;
import br.edu.unijui.gca.jabuti.JabutiStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JabutiIdeSetup extends JabutiStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JabutiRuntimeModule(), new JabutiIdeModule()));
	}
	
}
