/*
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JabutiStandaloneSetup extends JabutiStandaloneSetupGenerated {

	public static void doSetup() {
		new JabutiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
