/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti.impl;

import br.edu.unijui.gca.jabuti.jabuti.Clause;
import br.edu.unijui.gca.jabuti.jabuti.EventLog;
import br.edu.unijui.gca.jabuti.jabuti.JabutiPackage;
import br.edu.unijui.gca.jabuti.jabuti.Operation;
import br.edu.unijui.gca.jabuti.jabuti.RolePlayer;
import br.edu.unijui.gca.jabuti.jabuti.Terms;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Clause</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.impl.ClauseImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.impl.ClauseImpl#getEventLog <em>Event Log</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.impl.ClauseImpl#getOperation <em>Operation</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.impl.ClauseImpl#getTerms <em>Terms</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.impl.ClauseImpl#getRolePlayer <em>Role Player</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClauseImpl extends MinimalEObjectImpl.Container implements Clause
{
	/**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected static final String NAME_EDEFAULT = null;

	/**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
	protected String name = NAME_EDEFAULT;

	/**
	 * The cached value of the '{@link #getEventLog() <em>Event Log</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getEventLog()
	 * @generated
	 * @ordered
	 */
	protected EList<EventLog> eventLog;

	/**
	 * The default value of the '{@link #getOperation() <em>Operation</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOperation()
	 * @generated
	 * @ordered
	 */
	protected static final Operation OPERATION_EDEFAULT = Operation.PUSH;

	/**
	 * The cached value of the '{@link #getOperation() <em>Operation</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOperation()
	 * @generated
	 * @ordered
	 */
	protected Operation operation = OPERATION_EDEFAULT;

	/**
	 * The cached value of the '{@link #getTerms() <em>Terms</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getTerms()
	 * @generated
	 * @ordered
	 */
	protected Terms terms;

	/**
	 * The default value of the '{@link #getRolePlayer() <em>Role Player</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRolePlayer()
	 * @generated
	 * @ordered
	 */
	protected static final RolePlayer ROLE_PLAYER_EDEFAULT = RolePlayer.PROCESS;

	/**
	 * The cached value of the '{@link #getRolePlayer() <em>Role Player</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getRolePlayer()
	 * @generated
	 * @ordered
	 */
	protected RolePlayer rolePlayer = ROLE_PLAYER_EDEFAULT;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClauseImpl()
	{
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass()
	{
		return JabutiPackage.Literals.CLAUSE;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getName()
	{
		return name;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setName(String newName)
	{
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, JabutiPackage.CLAUSE__NAME, oldName, name));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EList<EventLog> getEventLog()
	{
		if (eventLog == null)
		{
			eventLog = new EObjectContainmentEList<EventLog>(EventLog.class, this, JabutiPackage.CLAUSE__EVENT_LOG);
		}
		return eventLog;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Operation getOperation()
	{
		return operation;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setOperation(Operation newOperation)
	{
		Operation oldOperation = operation;
		operation = newOperation == null ? OPERATION_EDEFAULT : newOperation;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, JabutiPackage.CLAUSE__OPERATION, oldOperation, operation));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Terms getTerms()
	{
		return terms;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetTerms(Terms newTerms, NotificationChain msgs)
	{
		Terms oldTerms = terms;
		terms = newTerms;
		if (eNotificationRequired())
		{
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JabutiPackage.CLAUSE__TERMS, oldTerms, newTerms);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setTerms(Terms newTerms)
	{
		if (newTerms != terms)
		{
			NotificationChain msgs = null;
			if (terms != null)
				msgs = ((InternalEObject)terms).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JabutiPackage.CLAUSE__TERMS, null, msgs);
			if (newTerms != null)
				msgs = ((InternalEObject)newTerms).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JabutiPackage.CLAUSE__TERMS, null, msgs);
			msgs = basicSetTerms(newTerms, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, JabutiPackage.CLAUSE__TERMS, newTerms, newTerms));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public RolePlayer getRolePlayer()
	{
		return rolePlayer;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setRolePlayer(RolePlayer newRolePlayer)
	{
		RolePlayer oldRolePlayer = rolePlayer;
		rolePlayer = newRolePlayer == null ? ROLE_PLAYER_EDEFAULT : newRolePlayer;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, JabutiPackage.CLAUSE__ROLE_PLAYER, oldRolePlayer, rolePlayer));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
	{
		switch (featureID)
		{
			case JabutiPackage.CLAUSE__EVENT_LOG:
				return ((InternalEList<?>)getEventLog()).basicRemove(otherEnd, msgs);
			case JabutiPackage.CLAUSE__TERMS:
				return basicSetTerms(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType)
	{
		switch (featureID)
		{
			case JabutiPackage.CLAUSE__NAME:
				return getName();
			case JabutiPackage.CLAUSE__EVENT_LOG:
				return getEventLog();
			case JabutiPackage.CLAUSE__OPERATION:
				return getOperation();
			case JabutiPackage.CLAUSE__TERMS:
				return getTerms();
			case JabutiPackage.CLAUSE__ROLE_PLAYER:
				return getRolePlayer();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue)
	{
		switch (featureID)
		{
			case JabutiPackage.CLAUSE__NAME:
				setName((String)newValue);
				return;
			case JabutiPackage.CLAUSE__EVENT_LOG:
				getEventLog().clear();
				getEventLog().addAll((Collection<? extends EventLog>)newValue);
				return;
			case JabutiPackage.CLAUSE__OPERATION:
				setOperation((Operation)newValue);
				return;
			case JabutiPackage.CLAUSE__TERMS:
				setTerms((Terms)newValue);
				return;
			case JabutiPackage.CLAUSE__ROLE_PLAYER:
				setRolePlayer((RolePlayer)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID)
	{
		switch (featureID)
		{
			case JabutiPackage.CLAUSE__NAME:
				setName(NAME_EDEFAULT);
				return;
			case JabutiPackage.CLAUSE__EVENT_LOG:
				getEventLog().clear();
				return;
			case JabutiPackage.CLAUSE__OPERATION:
				setOperation(OPERATION_EDEFAULT);
				return;
			case JabutiPackage.CLAUSE__TERMS:
				setTerms((Terms)null);
				return;
			case JabutiPackage.CLAUSE__ROLE_PLAYER:
				setRolePlayer(ROLE_PLAYER_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID)
	{
		switch (featureID)
		{
			case JabutiPackage.CLAUSE__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case JabutiPackage.CLAUSE__EVENT_LOG:
				return eventLog != null && !eventLog.isEmpty();
			case JabutiPackage.CLAUSE__OPERATION:
				return operation != OPERATION_EDEFAULT;
			case JabutiPackage.CLAUSE__TERMS:
				return terms != null;
			case JabutiPackage.CLAUSE__ROLE_PLAYER:
				return rolePlayer != ROLE_PLAYER_EDEFAULT;
		}
		return super.eIsSet(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String toString()
	{
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (name: ");
		result.append(name);
		result.append(", operation: ");
		result.append(operation);
		result.append(", rolePlayer: ");
		result.append(rolePlayer);
		result.append(')');
		return result.toString();
	}

} //ClauseImpl
