/*
 * generated by Xtext 2.31.0
 */
package br.edu.unijui.gca.jabuti.ui;

import br.edu.unijui.gca.jabuti.ui.internal.JabutiActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JabutiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JabutiActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JabutiActivator activator = JabutiActivator.getInstance();
		return activator != null ? activator.getInjector(JabutiActivator.BR_EDU_UNIJUI_GCA_JABUTI_JABUTI) : null;
	}

}
