/*
 * generated by Xtext 2.31.0
 */
package br.edu.unijui.gca.jabuti.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJabutiScopeProvider extends DelegatingScopeProvider {
}
