/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getName <em>Name</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getEventLog <em>Event Log</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getOperation <em>Operation</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getTerms <em>Terms</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getRolePlayer <em>Role Player</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getClause()
 * @model
 * @generated
 */
public interface Clause extends EObject
{
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getClause_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Event Log</b></em>' containment reference list.
	 * The list contents are of type {@link br.edu.unijui.gca.jabuti.jabuti.EventLog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Event Log</em>' containment reference list.
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getClause_EventLog()
	 * @model containment="true"
	 * @generated
	 */
	EList<EventLog> getEventLog();

	/**
	 * Returns the value of the '<em><b>Operation</b></em>' attribute.
	 * The default value is <code>""</code>.
	 * The literals are from the enumeration {@link br.edu.unijui.gca.jabuti.jabuti.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Operation</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.Operation
	 * @see #setOperation(Operation)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getClause_Operation()
	 * @model default=""
	 * @generated
	 */
	Operation getOperation();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getOperation <em>Operation</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Operation</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.Operation
	 * @see #getOperation()
	 * @generated
	 */
	void setOperation(Operation value);

	/**
	 * Returns the value of the '<em><b>Terms</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Terms</em>' containment reference.
	 * @see #setTerms(Terms)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getClause_Terms()
	 * @model containment="true" required="true"
	 * @generated
	 */
	Terms getTerms();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getTerms <em>Terms</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Terms</em>' containment reference.
	 * @see #getTerms()
	 * @generated
	 */
	void setTerms(Terms value);

	/**
	 * Returns the value of the '<em><b>Role Player</b></em>' attribute.
	 * The literals are from the enumeration {@link br.edu.unijui.gca.jabuti.jabuti.RolePlayer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Role Player</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.RolePlayer
	 * @see #setRolePlayer(RolePlayer)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getClause_RolePlayer()
	 * @model
	 * @generated
	 */
	RolePlayer getRolePlayer();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.Clause#getRolePlayer <em>Role Player</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Role Player</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.RolePlayer
	 * @see #getRolePlayer()
	 * @generated
	 */
	void setRolePlayer(RolePlayer value);

} // Clause
