/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
