/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getRight()
 * @model
 * @generated
 */
public interface Right extends Clause
{
} // Right
