/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terms</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Terms#getConditionalExpression <em>Conditional Expression</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.Terms#getExpressionTerm <em>Expression Term</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getTerms()
 * @model
 * @generated
 */
public interface Terms extends EObject
{
	/**
	 * Returns the value of the '<em><b>Conditional Expression</b></em>' containment reference list.
	 * The list contents are of type {@link br.edu.unijui.gca.jabuti.jabuti.ConditionalExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Conditional Expression</em>' containment reference list.
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getTerms_ConditionalExpression()
	 * @model containment="true"
	 * @generated
	 */
	EList<ConditionalExpression> getConditionalExpression();

	/**
	 * Returns the value of the '<em><b>Expression Term</b></em>' containment reference list.
	 * The list contents are of type {@link br.edu.unijui.gca.jabuti.jabuti.ExpressionTerm}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Expression Term</em>' containment reference list.
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getTerms_ExpressionTerm()
	 * @model containment="true"
	 * @generated
	 */
	EList<ExpressionTerm> getExpressionTerm();

} // Terms
