/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Term Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.UnaryTermOperator#getSymbol <em>Symbol</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.UnaryTermOperator#getExpressionTerm <em>Expression Term</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getUnaryTermOperator()
 * @model
 * @generated
 */
public interface UnaryTermOperator extends ExpressionTerm
{
	/**
	 * Returns the value of the '<em><b>Symbol</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Symbol</em>' attribute.
	 * @see #setSymbol(String)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getUnaryTermOperator_Symbol()
	 * @model
	 * @generated
	 */
	String getSymbol();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.UnaryTermOperator#getSymbol <em>Symbol</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Symbol</em>' attribute.
	 * @see #getSymbol()
	 * @generated
	 */
	void setSymbol(String value);

	/**
	 * Returns the value of the '<em><b>Expression Term</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Expression Term</em>' containment reference.
	 * @see #setExpressionTerm(ExpressionTerm)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getUnaryTermOperator_ExpressionTerm()
	 * @model containment="true"
	 * @generated
	 */
	ExpressionTerm getExpressionTerm();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.UnaryTermOperator#getExpressionTerm <em>Expression Term</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Expression Term</em>' containment reference.
	 * @see #getExpressionTerm()
	 * @generated
	 */
	void setExpressionTerm(ExpressionTerm value);

} // UnaryTermOperator
