/**
 * generated by Xtext 2.28.0
 */
package br.edu.unijui.gca.jabuti.jabuti;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Week Days Interval</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.WeekDaysInterval#getStart <em>Start</em>}</li>
 *   <li>{@link br.edu.unijui.gca.jabuti.jabuti.WeekDaysInterval#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getWeekDaysInterval()
 * @model
 * @generated
 */
public interface WeekDaysInterval extends Term
{
	/**
	 * Returns the value of the '<em><b>Start</b></em>' attribute.
	 * The literals are from the enumeration {@link br.edu.unijui.gca.jabuti.jabuti.WeekDay}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Start</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.WeekDay
	 * @see #setStart(WeekDay)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getWeekDaysInterval_Start()
	 * @model
	 * @generated
	 */
	WeekDay getStart();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.WeekDaysInterval#getStart <em>Start</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Start</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.WeekDay
	 * @see #getStart()
	 * @generated
	 */
	void setStart(WeekDay value);

	/**
	 * Returns the value of the '<em><b>End</b></em>' attribute.
	 * The literals are from the enumeration {@link br.edu.unijui.gca.jabuti.jabuti.WeekDay}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>End</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.WeekDay
	 * @see #setEnd(WeekDay)
	 * @see br.edu.unijui.gca.jabuti.jabuti.JabutiPackage#getWeekDaysInterval_End()
	 * @model
	 * @generated
	 */
	WeekDay getEnd();

	/**
	 * Sets the value of the '{@link br.edu.unijui.gca.jabuti.jabuti.WeekDaysInterval#getEnd <em>End</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>End</em>' attribute.
	 * @see br.edu.unijui.gca.jabuti.jabuti.WeekDay
	 * @see #getEnd()
	 * @generated
	 */
	void setEnd(WeekDay value);

} // WeekDaysInterval
